CREATE TABLE IF NOT EXISTS rate_limit_policies (
    policy_key VARCHAR(128) PRIMARY KEY,
    request_limit BIGINT NOT NULL,
    window_seconds BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
